version: 2

sphinx:
  configuration: doc/source/conf.py

sphinx:
  configuration: docs/conf.py

python:
  version: 3.12
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
