name: Deploy docs

on:
    push:
        branches:
            - main
            - dev1

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11
            
            - name: Install dependencies
              run: |
                pip install -r docs/requirements-doc.txt
                
            - name: Build docs
              run: |
                sphinx-build -M html docs/source docs/build

            - name: Deploy to GitHub Pages
              if: github.ref == 'refs/heads/dev1'
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: docs/build/html
