name: Tests

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # Adjust as necessary based on your setup

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies with Poetry
        run: poetry install
      - name: Run mypy
        run: poetry run tox -e mypy
      - name: Run ruff
        run: poetry run tox -e ruff